# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b58b15ba6f5154a20de159a5fdf9501ab8232671c8864a4ce475f9b49a5423e5c9137a0c3ea8fb0bdd7bbc4abe27dea49851b78f48883e250058642ac209e0e

test:
  secret_key_base: e90b7907c72e468c25446742283a9d35ec67100ff5f137e1398d57e70e908af0a0d9d29513809d3548a58a82ee3d720634c1745ce4fb4199ced5834cbf99c50a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
